name: Build

on:
  push:
    branches: [ main ]
    tags: [ v* ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin

      - name: Build application
        run: make build

      - name: Docker image
        run: make docker

      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker images [edge]
        run: |
          docker tag schunit/schunit:dev schunit/schunit:edge
          docker push schunit/schunit:edge
          docker tag schunit/devcontainer:dev schunit/devcontainer:edge
          docker push schunit/devcontainer:edge

      - name: Set version
        if: startsWith(github.ref, 'refs/tags/')
        env:
          REF: ${{ github.ref }}
        run: echo "VERSION=$(echo $REF | sed 's:refs/tags/v::' )" >> $GITHUB_ENV

      - name: Push docker images [release]
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          docker tag schunit/schunit:dev schunit/schunit:${VERSION}
          docker tag schunit/schunit:dev schunit/schunit:latest
          docker push schunit/schunit:${VERSION}
          docker push schunit/schunit:latest
          docker tag schunit/devcontainer:dev schunit/devcontainer:${VERSION}
          docker tag schunit/devcontainer:dev schunit/devcontainer:latest
          docker push schunit/devcontainer:${VERSION}
          docker push schunit/devcontainer:latest

      - name: Upload cli distribution (tar.gz)
        uses: klakegg/github-upload@v0.9.1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: schunit-cli/target/schunit-cli-${VERSION}-dist.tar.gz
          label: SchUnit Cli (tar.gz)

      - name: Upload cli distribution (zip)
        uses: klakegg/github-upload@v0.9.1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: schunit-cli/target/schunit-cli-${VERSION}-dist.zip
          label: SchUnit Cli (zip)

      - name: Upload core distribution (tar.gz)
        uses: klakegg/github-upload@v0.9.1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: schunit-core/target/schunit-core-${VERSION}-dist.tar.gz
          label: SchUnit Core Library (tar.gz)

      - name: Upload core distribution (zip)
        uses: klakegg/github-upload@v0.9.1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: schunit-core/target/schunit-core-${VERSION}-dist.zip
          label: SchUnit Core Library (zip)
